name: openadmet-demos
channels:
  - conda-forge
  - defaults
dependencies:
  - ase
  - chemprop >= 2.1.1
  - codecov
  - datamol
  - jupyterlab
  - lightgbm
  - loguru
  - matplotlib
  - mordredcommunity
  - numpy
  - pandas
  - pingouin
  - pip
  - python >= 3.12
  - pytorch
  - pytorch-lightning
  - pytorch_cluster
  - pytorch_geometric
  - pytorch_scatter
  - pytorch_sparse
  - pytest
  - pytest-cov
  - pytest-xdist
  - openff-units
  - rdkit
  - rich
  - scikit-learn
  - seaborn
  - splito
  - statsmodels
  - tabulate
  - uncertainty-toolbox
  - wandb
  - xgboost
  - zarr >=3.0.0
  - pip:
    - phx-class-registry
    - git+https://github.com/OpenADMET/openadmet-models.git
    - git+https://github.com/OpenADMET/openadmet-toolkit.git
    - mols2grid
    - git+https://github.com/OpenADMET/molfeat.git@main

