data:
  anvil_dir: file:///data1/choderaj/openadmet/openadmet-demos/demos/04_Ensemble_Model_Training
  cat_entry: null
  dropna: true
  input_col: OPENADMET_CANONICAL_SMILES
  resource: ../01_Data_Curation/processed_data/processed_CYP3A4_inhibition.csv
  target_cols:
  - OPENADMET_LOGAC50
  type: intake
metadata:
  authors: Your Name
  biotargets:
  - CYP3A4
  build_number: 0
  description: basic regression using a LightGBM model
  driver: sklearn
  email: youremail@email.com
  name: lgbm_pchembl
  tag: openadmet-chembl
  tags:
  - openadmet
  - test
  - pchembl
  version: v1
procedure:
  ensemble:
    calibration_method: scaling-factor
    n_models: 5
    param_paths: null
    params: {}
    serial_paths: null
    type: CommitteeRegressor
  feat:
    params:
      featurizers:
        DescriptorFeaturizer:
          descr_type: desc2d
        FingerprintFeaturizer:
          fp_type: ecfp:4
    type: FeatureConcatenator
  model:
    freeze_weights: null
    param_path: null
    params:
      alpha: 0.005
      learning_rate: 0.05
      n_estimators: 500
    serial_path: null
    type: LGBMRegressorModel
  split:
    params:
      random_state: 42
      test_size: 0.2
      train_size: 0.7
      val_size: 0.1
    type: ShuffleSplitter
  train:
    params: {}
    type: SKLearnBasicTrainer
  transform: null
report:
  eval:
  - params: {}
    type: RegressionMetrics
  - params:
      axes_labels:
      - True pAC50
      - Predicted pAC50
      max_val: 10
      min_val: 3
      n_repeats: 5
      n_splits: 5
      pXC50: true
      title: True vs Predicted pAC50 on test set
    type: RegressionPlots
  - params:
      bins: 100
      resolution: 99
      scaled: true
    type: UncertaintyMetrics
  - params: {}
    type: UncertaintyPlots
