name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"  # weekly run

jobs:
  test:
    name: Test Notebooks on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: openadmet-demos.yaml
          environment-name: openadmet-demos
          condarc: |
            channels:
              - conda-forge
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Run notebooks with pytest-nbmake
        uses: mamba-org/run-in-micromamba@v1
        with:
          environment-file: openadmet-demos.yaml
          environment-name: openadmet-demos
          # This shell block will execute inside the activated micromamba env
          run: |
            # Verify environment
            micromamba list

            # Run all notebooks
            pytest --nbmake --maxfail=1 --disable-warnings **/*.ipynb

      - name: CodeCov
        uses: codecov/codecov-action@v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}

