name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run at 5:30 UTC every Monday
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.12"]

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Display system info for debugging
      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # Setup micromamba and create environment
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: openadmet-demos
          condarc: |
            channels:
              - conda-forge
          create-args: >-
            python=${{ matrix.python-version }}

      # Activate environment and run notebooks
      - name: Install pytest-nbmake & demos
        shell: bash -l {0}
        run: |
          python -m pip install .
          python -m pip install nbmake pytest-xdist

      - name: Run tests with pytest-nbmake
        shell: bash -l {0}
        run: |
          pytest -n=auto --nbmake --nbmake-timeout=1200 --maxfail=0 --disable-warnings .
